# Generated by Django 4.2.30 on 2026-06-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tracksection',
            constraint=models.UniqueConstraint(fields=('start_station', 'end_station', 'direction'), name='uniq_track_route_direction'),
        ),
    ]
