# Generated by Django 4.2.30 on 2026-06-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0002_tracksection_uniq_track_route_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracksection',
            name='geometry',
            field=models.JSONField(blank=True, default=list, help_text='Leaflet-compatible polyline coordinates as [[lat, lng], ...]. Used by the map API to render route lines without a separate GeoJSON file.'),
        ),
    ]
